version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - example-db:/var/lib/postgresql/data
example:
    build:
      context: .
    environment:
      PROD_DB_NAME: task_manager
      PROD_DB_USERNAME: postgres
      PROD_DB_PASSWORD: admin
      PROD_DB_HOSTNAME: localhost
    depends_on:
      - postgres
    ports:
      - "3000:3000"
volumes:
  example-db: